Repository opendatalab/MinerU, pull requests merged in 2025-09, with the labels that each got.

#3374 fix error logs for multi_gpu endpoint.
  projects/multi_gpu_v2/_config_endpoint.py
Labels: bug, size:XS

#3421 Dev
  mineru/backend/pipeline/model_json_to_middle_json.py
  mineru/backend/vlm/token_to_middle_json.py
  mineru/utils/draw_bbox.py
  mineru/utils/table_merge.py
Labels: size:L

#3427 Dev
  README.md
  README_zh-CN.md
  pyproject.toml
Labels: size:XS

#3429 master->dev
  mineru/version.py
Labels: size:XS

#3448 fix: improve HTML code handling and logging in batch_analyze and main…
  mineru/backend/pipeline/batch_analyze.py
  mineru/model/table/rec/unet_table/main.py
Labels: size:XS

#3449 docs: update changelog for version 2.2.2 release
  README.md
  README_zh-CN.md
Labels: size:XS

#3504 update docs
  docs/en/reference/output_files.md
  docs/en/usage/cli_tools.md
  docs/en/usage/quick_usage.md
  docs/zh/reference/output_files.md
  docs/zh/usage/cli_tools.md
  docs/zh/usage/quick_usage.md
Labels: size:L

#3505 update docs
  docs/en/reference/output_files.md
  docs/en/usage/cli_tools.md
  docs/en/usage/quick_usage.md
  docs/zh/reference/output_files.md
  docs/zh/usage/cli_tools.md
  docs/zh/usage/quick_usage.md
Labels: size:M

#3506 Dev
  docs/en/reference/output_files.md
  docs/en/usage/cli_tools.md
  docs/en/usage/quick_usage.md
  docs/zh/reference/output_files.md
  docs/zh/usage/cli_tools.md
  docs/zh/usage/quick_usage.md
  mkdocs.yml
Labels: size:L

#3512 update docs
  docs/en/usage/quick_usage.md
Labels: size:XS

#3514 update dependencies
  pyproject.toml
Labels: size:XS

#3513 Release 2.5.0
  README.md
  README_zh-CN.md
  docs/en/usage/quick_usage.md
  pyproject.toml
Labels: documentation, size:S

#3515 master->dev
  docs/en/usage/quick_usage.md
  mineru/cli/gradio_app.py
  mineru/version.py
  pyproject.toml
Labels: size:S

#3516 Update dependency name for mineru-vl-utils in pyproject.toml
  pyproject.toml
Labels: size:XS

#3527 fix: Update mineru-vl-utils version and add logits processors support
  README.md
  README_zh-CN.md
  mineru/backend/vlm/vlm_analyze.py
  mineru/model/vlm_vllm_model/server.py
  pyproject.toml
Labels: enhancement, size:S

#3532 Fix formatting in vlm_middle_json_mkcontent.py to ensure proper line breaks in list items
  README.md
  README_zh-CN.md
  mineru/backend/vlm/vlm_middle_json_mkcontent.py
Labels: size:XS

#3534 Release 2.5.2
  README.md
  README_zh-CN.md
  mineru/backend/vlm/vlm_middle_json_mkcontent.py
Labels: size:XS

#3535 master->dev
  mineru/version.py
Labels: size:XS

#3546 Update docker_deployment.md for improved clarity on base image usage …
  docs/zh/quick_start/docker_deployment.md
Labels: documentation, size:XS

#3549 Update README.md and README_zh-CN.md to include changelog for v2.5.3 …
  README.md
  README_zh-CN.md
Labels: documentation, size:S

#3551 Fix compute capability comparison in custom_logits_processors.py for …
  mineru/backend/vlm/custom_logits_processors.py
Labels: size:XS

#3553 Fix formatting in changelog sections of README.md and README_zh-CN.md…
  README.md
  README_zh-CN.md
Labels: size:S

#3554 Fix formatting in changelog sections of README.md and README_zh-CN.md…
  README.md
  README_zh-CN.md
Labels: size:XS

#3555 Dev
  README.md
  README_zh-CN.md
Labels: size:S

#3556 Refactor batch image orientation classification logic for improved cl…
  mineru/backend/pipeline/batch_analyze.py
Labels: size:S

#3557 Dev
  mineru/backend/pipeline/batch_analyze.py
Labels: size:S

#3558 master->dev
  mineru/version.py
Labels: size:XS

#3563 Update model output handling in test_e2e.py to write JSON format instead of text
  tests/unittest/test_e2e.py
Labels: size:XS

#3606 Dev
  mineru/cli/common.py
  mineru/cli/gradio_app.py
  mineru/utils/guess_suffix_or_lang.py
Labels: documentation, size:S

#3607 Update changelog for version 2.5.4 to document PDF identification fix
  README.md
  README_zh-CN.md
Labels: size:XS

#3608 Release 2.5.4
  README.md
  README_zh-CN.md
  mineru/cli/common.py
  mineru/cli/gradio_app.py
  mineru/utils/guess_suffix_or_lang.py
  pyproject.toml
  tests/unittest/test_e2e.py
Labels: documentation, size:M

#3610 master->dev
  mineru/version.py
  pyproject.toml
Labels: size:XS

#3615 docs: Add MinerU2.5 technical report and BibTeX
  README.md
  README_zh-CN.md
Labels: documentation, size:S
