Repository opendatalab/MinerU, pull requests merged in 2025-07, with the labels that each got.

#2975 fix: add Noto fonts installation for Chinese character support in Dockerfile
  docker/china/Dockerfile
  docker/global/Dockerfile
  mineru/backend/pipeline/model_json_to_middle_json.py
Labels: size:S

#2990 feat: simplify heading level feature configuration and error handling
  mineru/backend/vlm/token_to_middle_json.py
Labels: enhancement, size:S

#3016 Dev
  README_zh-CN.md
  docker/compose.yaml
  docs/en/index.md
  docs/en/quick_start/docker_deployment.md
  docs/en/quick_start/extension_modules.md
  docs/en/quick_start/index.md
  docs/en/usage/advanced_cli_parameters.md
  docs/en/usage/cli_tools.md
  docs/en/usage/index.md
  docs/en/usage/model_source.md
  docs/mineru.template.json
  docs/zh/FAQ/index.md
  docs/zh/index.md
  docs/zh/known_issues.md
  docs/zh/quick_start/docker_deployment.md
  docs/zh/quick_start/extension_modules.md
  docs/zh/quick_start/index.md
  docs/zh/quick_start/local_deployment.md
  docs/zh/quick_start/online_demo.md
  docs/zh/todo.md
  docs/zh/usage/advanced_cli_parameters.md
  docs/zh/usage/api.md
  docs/zh/usage/cli_tools.md
  docs/zh/usage/config.md
  docs/zh/usage/index.md
  docs/zh/usage/model_source.md
  docs/zh/usage/output_file.md
  mineru/backend/vlm/token_to_middle_json.py
  mineru/utils/model_utils.py
  mkdocs.yml
Labels: size:XXL

#3018 docs: improve clarity and formatting in advanced_cli_parameters.md, docker_deployment.md, and index.md
  docs/zh/quick_start/docker_deployment.md
  docs/zh/quick_start/index.md
  docs/zh/usage/advanced_cli_parameters.md
Labels: size:S

#3019 Dev
  docs/zh/quick_start/docker_deployment.md
  docs/zh/usage/advanced_cli_parameters.md
  docs/zh/usage/index.md
Labels: documentation, size:S

#3023 Dev
  docs/en/usage/output_files.md
  docs/zh/usage/output_file.md
  docs/zh/usage/output_files.md
  mkdocs.yml
Labels: size:XL

#3067 test: reconstruct test_e2e.py and feishubot
  .github/workflows/cli.yml
  .github/workflows/huigui.yml
  tests/unittest/test_e2e.py
Labels: enhancement, size:M

#3073 test: remove requirements-qa.txt
  requirements-qa.txt
Labels: size:S

#3105 test: remove huigui.yml
  .github/workflows/cli.yml
  .github/workflows/huigui.yml
Labels: size:M

#3125 Dev
  .github/workflows/cli.yml
  .github/workflows/huigui.yml
  pyproject.toml
Labels: size:M

#3129 improve the caption match algorithm
  mineru/backend/pipeline/pipeline_magic_model.py
Labels: enhancement, size:XS

#3140 docs: update changelog for version 2.1.2 with bug fixes
  README.md
  README_zh-CN.md
Labels: size:XS

#3144 Release 2.1.3
  README.md
  README_zh-CN.md
  mineru/model/mfr/unimernet/Unimernet.py
Labels: documentation, size:XS

#3156 Release 2.1.4
  README.md
  README_zh-CN.md
Labels: size:XS

#3175 Fix draw bbox when pdf rotate.
  mineru/utils/draw_bbox.py
Labels: bug, size:M

#3181 refactor: enhance HTML table extraction and add block content conversion to HTML
  mineru/backend/pipeline/batch_analyze.py
  mineru/backend/vlm/vlm_magic_model.py
  mineru/utils/draw_bbox.py
  mineru/utils/format_utils.py
Labels: bug, enhancement, size:M

#3182 Dev
  README.md
  README_zh-CN.md
Labels: size:XS

#3183 Release 2.1.6
  README.md
  README_zh-CN.md
  mineru/backend/pipeline/batch_analyze.py
  mineru/backend/vlm/vlm_magic_model.py
  mineru/utils/draw_bbox.py
  mineru/utils/format_utils.py
Labels: size:L

#3186 fix: update past_key_values handling to support custom sequence lengths
  README.md
  README_zh-CN.md
  docker/china/Dockerfile
  docker/global/Dockerfile
  docs/en/quick_start/docker_deployment.md
  docs/zh/quick_start/docker_deployment.md
  mineru/model/mfr/unimernet/unimernet_hf/unimer_mbart/modeling_unimer_mbart.py
Labels: documentation, size:M

#3187 Release 2.1.7
  README.md
  README_zh-CN.md
  docker/china/Dockerfile
  docker/global/Dockerfile
  docs/en/quick_start/docker_deployment.md
  docs/zh/quick_start/docker_deployment.md
  mineru/model/mfr/unimernet/unimernet_hf/unimer_mbart/modeling_unimer_mbart.py
Labels: size:M

#3222 Set sglang base image to DaoCloud mirror for China Users.
  docker/china/Dockerfile
Labels: size:XS
