Repository opendatalab/MinerU, pull requests merged in 2025-08, with the labels that each got.

#3275 Dev
  mineru/backend/pipeline/batch_analyze.py
  mineru/backend/pipeline/model_init.py
  mineru/backend/pipeline/model_json_to_middle_json.py
  mineru/backend/pipeline/pipeline_analyze.py
  mineru/backend/vlm/token_to_middle_json.py
  mineru/backend/vlm/vlm_analyze.py
  mineru/model/layout/doclayout_yolo.py
  mineru/model/ocr/paddleocr2pytorch/pytorch_paddle.py
  mineru/model/ori_cls/paddle_ori_cls.py
  mineru/model/table/cls/paddle_table_cls.py
  mineru/model/table/rec/rapid_table.py
  mineru/model/table/rec/unet_table/table_line_rec_utils.py
  mineru/model/table/rec/unet_table/unet_table.py
  mineru/utils/enum_class.py
  mineru/utils/model_utils.py
  mineru/utils/pdf_classify.py
  mineru/utils/pdf_image_tools.py
  mineru/utils/pdf_reader.py
Labels: size:L

#3325 fix: improve bounding box update logic based on score comparison
  mineru/utils/model_utils.py
Labels: size:M

#3281 feat: support return parse result by zip
  mineru/cli/fast_api.py
Labels: enhancement, size:L

#3371 Feat: add batch predict for table rec
  mineru/backend/pipeline/batch_analyze.py
  mineru/backend/pipeline/model_init.py
  mineru/model/ori_cls/paddle_ori_cls.py
  mineru/model/table/cls/paddle_table_cls.py
  mineru/model/table/rec/rapid_table.py
  mineru/model/table/rec/slanet_plus/__init__.py
  mineru/model/table/rec/slanet_plus/main.py
  mineru/model/table/rec/slanet_plus/matcher.py
  mineru/model/table/rec/slanet_plus/matcher_utils.py
  mineru/model/table/rec/slanet_plus/table_structure.py
  mineru/model/table/rec/slanet_plus/table_structure_utils.py
  mineru/model/table/rec/unet_table/main.py
  pyproject.toml
Labels: enhancement, size:XXL

#3383 Dev
  mineru/backend/pipeline/batch_analyze.py
  mineru/model/table/rec/unet_table/utils.py
Labels: size:S

#3396 Dev
  mineru/backend/pipeline/batch_analyze.py
  mineru/backend/pipeline/model_init.py
  mineru/backend/vlm/hf_predictor.py
  mineru/model/ori_cls/paddle_ori_cls.py
  mineru/model/table/cls/paddle_table_cls.py
  mineru/model/table/rec/RapidTable.py
  mineru/model/table/rec/slanet_plus/main.py
  mineru/model/table/rec/unet_table/main.py
  mineru/model/table/rec/unet_table/utils_table_line_rec.py
  mineru/utils/model_utils.py
  pyproject.toml
Labels: size:L

#3397 Dev
  mineru/backend/pipeline/batch_analyze.py
  mineru/model/table/rec/unet_table/main.py
Labels: size:XS
